[package]
name = "cputopenssl"
version = "0.1.0"
authors = ["Michael Mera <dev@michaelmera.com>"]
edition = "2021"

[features]
default = []

[dependencies]
cmake = "0.1"
tlspuffin-cbindings = { path = "../../cbindings" }