[package]
name = "security-claims"
build = "build.rs"
description = "Optional instrumentation for PUTs"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
hex = "0.4.3"
itertools = "0.10.3"

[build-dependencies]
bindgen = "0.60.1"
